#INDEX
GET http://localhost:3000/products.json

###
#SHOW
GET http://localhost:3000/products/3.json

###

POST http://localhost:3000/products.json
content-type: application/json

{
"name": "Mike",
"price": 1000000,
"url": "   ",
"description": "here is the sescription"

}