Product.create!([      
  {name: "Kale", price: 8, img_url: "https://loremflickr.com/300/300", description: "28-day aged 300g USDA Certified Prime Ribeye, rosemary-thyme garlic butter, with choice of two sides."},
  {name: "Fresh Chillies", price: 2, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles. Served with maple syrup."},
  {name: "Broccolini", price: 4, img_url: "https://loremflickr.com/300/300", description: "Smoked salmon, poached eggs, diced red onions and Hollandaise sauce on an English muffin. With a side of roasted potatoes."},
  {name: "English Spinach", price: 5, img_url: "https://loremflickr.com/300/300", description: "Three egg omelet with Roquefort cheese, chives, and ham. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Capers", price: 1, img_url: "https://loremflickr.com/300/300", description: "Granny Smith apples mixed with brown sugar and butter filling, in a flaky all-butter crust, with ice cream."},
  {name: "Red cabbage", price: 1, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles. Served with maple syrup."},
  {name: "Bean Shoots", price: 1, img_url: "https://loremflickr.com/300/300", description: "Granny Smith apples mixed with brown sugar and butter filling, in a flaky all-butter crust, with ice cream."},
  {name: "Red Pepper", price: 7, img_url: "https://loremflickr.com/300/300", description: "Three eggs with cilantro, tomatoes, onions, avocados and melted Emmental cheese. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Kale", price: 1, img_url: "https://loremflickr.com/300/300", description: "Thick slices of French toast bread, brown sugar, half-and-half and vanilla, topped with powdered sugar. With two eggs served any style, and your choice of smoked bacon or smoked ham."},
  {name: "Eggplant", price: 0, img_url: "https://loremflickr.com/300/300", description: "Granny Smith apples mixed with brown sugar and butter filling, in a flaky all-butter crust, with ice cream."},
  {name: "Onion", price: 6, img_url: "https://loremflickr.com/300/300", description: "Smoked salmon, poached eggs, diced red onions and Hollandaise sauce on an English muffin. With a side of roasted potatoes."},
  {name: "Purple carrot", price: 7, img_url: "https://loremflickr.com/300/300", description: "Granny Smith apples mixed with brown sugar and butter filling, in a flaky all-butter crust, with ice cream."},
  {name: "Cornichons", price: 3, img_url: "https://loremflickr.com/300/300", description: "Granny Smith apples mixed with brown sugar and butter filling, in a flaky all-butter crust, with ice cream."},
  {name: "Capers", price: 9, img_url: "https://loremflickr.com/300/300", description: "Three egg whites with spinach, mushrooms, caramelized onions, tomatoes and low-fat feta cheese. With herbed quinoa, and your choice of rye or whole-grain toast."},
  {name: "Beans", price: 9, img_url: "https://loremflickr.com/300/300", description: "Three egg whites with spinach, mushrooms, caramelized onions, tomatoes and low-fat feta cheese. With herbed quinoa, and your choice of rye or whole-grain toast."},
  {name: "Fresh Chillies", price: 2, img_url: "https://loremflickr.com/300/300", description: "Fresh Norwegian salmon, lightly brushed with our herbed Dijon mustard sauce, with choice of two sides."},
  {name: "Bean Shoots", price: 3, img_url: "https://loremflickr.com/300/300", description: "Granny Smith apples mixed with brown sugar and butter filling, in a flaky all-butter crust, with ice cream."},
  {name: "Butternut lettuce", price: 6, img_url: "https://loremflickr.com/300/300", description: "Three eggs with cilantro, tomatoes, onions, avocados and melted Emmental cheese. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Radicchio", price: 5, img_url: "https://loremflickr.com/300/300", description: "Three egg whites with spinach, mushrooms, caramelized onions, tomatoes and low-fat feta cheese. With herbed quinoa, and your choice of rye or whole-grain toast."},
  {name: "Parsnip", price: 3, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles. Served with maple syrup."},
  {name: "Kale", price: 3, img_url: "https://loremflickr.com/300/300", description: "Three egg omelet with Roquefort cheese, chives, and ham. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Lettuce", price: 1, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles. Served with maple syrup."},
  {name: "Iceberg lettuce", price: 2, img_url: "https://loremflickr.com/300/300", description: "Fresh Norwegian salmon, lightly brushed with our herbed Dijon mustard sauce, with choice of two sides."},
  {name: "Garlic", price: 3, img_url: "https://loremflickr.com/300/300", description: "28-day aged 300g USDA Certified Prime Ribeye, rosemary-thyme garlic butter, with choice of two sides."},
  {name: "Kohlrabi", price: 9, img_url: "https://loremflickr.com/300/300", description: "Three eggs with cilantro, tomatoes, onions, avocados and melted Emmental cheese. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Radicchio", price: 1, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles. Served with maple syrup."},
  {name: "Kale", price: 8, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles. Served with maple syrup."},
  {name: "Iceberg lettuce", price: 6, img_url: "https://loremflickr.com/300/300", description: "Smoked salmon, poached eggs, diced red onions and Hollandaise sauce on an English muffin. With a side of roasted potatoes."},
  {name: "Sun dried tomatoes", price: 7, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles, and a side of maple syrup."},
  {name: "Sun dried tomatoes", price: 4, img_url: "https://loremflickr.com/300/300", description: "Three eggs with cilantro, tomatoes, onions, avocados and melted Emmental cheese. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Broccolini", price: 9, img_url: "https://loremflickr.com/300/300", description: "Three egg omelet with Roquefort cheese, chives, and ham. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Butternut lettuce", price: 8, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles. Served with maple syrup."},
  {name: "Snowpea sprouts", price: 1, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles. Served with maple syrup."},
  {name: "French eschallots", price: 2, img_url: "https://loremflickr.com/300/300", description: "Creamy mascarpone cheese and custard layered between espresso and rum soaked house-made ladyfingers, topped with Valrhona cocoa powder."},
  {name: "Asparagus", price: 6, img_url: "https://loremflickr.com/300/300", description: "Three egg whites with spinach, mushrooms, caramelized onions, tomatoes and low-fat feta cheese. With herbed quinoa, and your choice of rye or whole-grain toast."},
  {name: "Cos lettuce", price: 5, img_url: "https://loremflickr.com/300/300", description: "Smoked salmon, poached eggs, diced red onions and Hollandaise sauce on an English muffin. With a side of roasted potatoes."},
  {name: "Peas", price: 0, img_url: "https://loremflickr.com/300/300", description: "Three egg whites with spinach, mushrooms, caramelized onions, tomatoes and low-fat feta cheese. With herbed quinoa, and your choice of rye or whole-grain toast."},
  {name: "Broccoli", price: 0, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles, and a side of maple syrup."},
  {name: "English Spinach", price: 5, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles. Served with maple syrup."},
  {name: "Endive", price: 4, img_url: "https://loremflickr.com/300/300", description: "Three egg whites with spinach, mushrooms, caramelized onions, tomatoes and low-fat feta cheese. With herbed quinoa, and your choice of rye or whole-grain toast."},
  {name: "Swiss Chard", price: 2, img_url: "https://loremflickr.com/300/300", description: "Three egg omelet with Roquefort cheese, chives, and ham. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Cos lettuce", price: 2, img_url: "https://loremflickr.com/300/300", description: "Thick slices of French toast bread, brown sugar, half-and-half and vanilla, topped with powdered sugar. With two eggs served any style, and your choice of smoked bacon or smoked ham."},
  {name: "Garlic", price: 5, img_url: "https://loremflickr.com/300/300", description: "Two buttermilk waffles, topped with whipped cream and maple syrup, a side of two eggs served any style, and your choice of smoked bacon or smoked ham."},
  {name: "Squash", price: 9, img_url: "https://loremflickr.com/300/300", description: "Three egg omelet with Roquefort cheese, chives, and ham. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Beans", price: 7, img_url: "https://loremflickr.com/300/300", description: "Granny Smith apples mixed with brown sugar and butter filling, in a flaky all-butter crust, with ice cream."},
  {name: "Beetroot", price: 2, img_url: "https://loremflickr.com/300/300", description: "Creamy mascarpone cheese and custard layered between espresso and rum soaked house-made ladyfingers, topped with Valrhona cocoa powder."},
  {name: "Iceberg lettuce", price: 4, img_url: "https://loremflickr.com/300/300", description: "Fresh parsley, Italian sausage, shallots, garlic, sun-dried tomatoes and mozzarella cheese in an all-butter crust. With a side of mixed fruits."},
  {name: "Kohlrabi", price: 9, img_url: "https://loremflickr.com/300/300", description: "Fresh Norwegian salmon, lightly brushed with our herbed Dijon mustard sauce, with choice of two sides."},
  {name: "Green beans", price: 2, img_url: "https://loremflickr.com/300/300", description: "Two buttermilk waffles, topped with whipped cream and maple syrup, a side of two eggs served any style, and your choice of smoked bacon or smoked ham."},
  {name: "Bean Sprouts", price: 2, img_url: "https://loremflickr.com/300/300", description: "Two buttermilk waffles, topped with whipped cream and maple syrup, a side of two eggs served any style, and your choice of smoked bacon or smoked ham."},
  {name: "Purple carrot", price: 4, img_url: "https://loremflickr.com/300/300", description: "Smoked salmon, poached eggs, diced red onions and Hollandaise sauce on an English muffin. With a side of roasted potatoes."},
  {name: "Red Pepper", price: 3, img_url: "https://loremflickr.com/300/300", description: "Smoked salmon, poached eggs, diced red onions and Hollandaise sauce on an English muffin. With a side of roasted potatoes."},
  {name: "Eggplant", price: 5, img_url: "https://loremflickr.com/300/300", description: "Fresh Norwegian salmon, lightly brushed with our herbed Dijon mustard sauce, with choice of two sides."},
  {name: "Celery", price: 2, img_url: "https://loremflickr.com/300/300", description: "Thick slices of French toast bread, brown sugar, half-and-half and vanilla, topped with powdered sugar. With two eggs served any style, and your choice of smoked bacon or smoked ham."},
  {name: "Radicchio", price: 8, img_url: "https://loremflickr.com/300/300", description: "Fresh parsley, Italian sausage, shallots, garlic, sun-dried tomatoes and mozzarella cheese in an all-butter crust. With a side of mixed fruits."},
  {name: "Green Pepper", price: 3, img_url: "https://loremflickr.com/300/300", description: "Thick slices of French toast bread, brown sugar, half-and-half and vanilla, topped with powdered sugar. With two eggs served any style, and your choice of smoked bacon or smoked ham."},
  {name: "Cucumber", price: 7, img_url: "https://loremflickr.com/300/300", description: "Thick slices of French toast bread, brown sugar, half-and-half and vanilla, topped with powdered sugar. With two eggs served any style, and your choice of smoked bacon or smoked ham."},
  {name: "Cucumber", price: 4, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles. Served with maple syrup."},
  {name: "Squash", price: 9, img_url: "https://loremflickr.com/300/300", description: "Three egg whites with spinach, mushrooms, caramelized onions, tomatoes and low-fat feta cheese. With herbed quinoa, and your choice of rye or whole-grain toast."},
  {name: "Asian Greens", price: 4, img_url: "https://loremflickr.com/300/300", description: "Three egg whites with spinach, mushrooms, caramelized onions, tomatoes and low-fat feta cheese. With herbed quinoa, and your choice of rye or whole-grain toast."},
  {name: "English Spinach", price: 8, img_url: "https://loremflickr.com/300/300", description: "Three egg whites with spinach, mushrooms, caramelized onions, tomatoes and low-fat feta cheese. With herbed quinoa, and your choice of rye or whole-grain toast."},
  {name: "Spinach", price: 5, img_url: "https://loremflickr.com/300/300", description: "Two butter croissants of your choice (plain, almond or cheese). With a side of herb butter or house-made hazelnut spread."},
  {name: "Onion", price: 3, img_url: "https://loremflickr.com/300/300", description: "Two buttermilk waffles, topped with whipped cream and maple syrup, a side of two eggs served any style, and your choice of smoked bacon or smoked ham."},
  {name: "Green Pepper", price: 8, img_url: "https://loremflickr.com/300/300", description: "28-day aged 300g USDA Certified Prime Ribeye, rosemary-thyme garlic butter, with choice of two sides."},
  {name: "Dried Chinese Broccoli", price: 4, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles. Served with maple syrup."},
  {name: "Bean Sprouts", price: 6, img_url: "https://loremflickr.com/300/300", description: "Creamy mascarpone cheese and custard layered between espresso and rum soaked house-made ladyfingers, topped with Valrhona cocoa powder."},
  {name: "Chilli Pepper", price: 4, img_url: "https://loremflickr.com/300/300", description: "Three eggs with cilantro, tomatoes, onions, avocados and melted Emmental cheese. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Leeks", price: 7, img_url: "https://loremflickr.com/300/300", description: "Creamy mascarpone cheese and custard layered between espresso and rum soaked house-made ladyfingers, topped with Valrhona cocoa powder."},
  {name: "Mike", price: 1000000, img_url: "   ", description: "here is the sescription"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "French eschallots", price: 2, img_url: "https://loremflickr.com/300/300", description: "Fresh Norwegian salmon, lightly brushed with our herbed Dijon mustard sauce, with choice of two sides."},
  {name: "Purple carrot", price: 1, img_url: "https://loremflickr.com/300/300", description: "Three egg whites with spinach, mushrooms, caramelized onions, tomatoes and low-fat feta cheese. With herbed quinoa, and your choice of rye or whole-grain toast."},
  {name: "Turnips", price: 6, img_url: "https://loremflickr.com/300/300", description: "Fresh parsley, Italian sausage, shallots, garlic, sun-dried tomatoes and mozzarella cheese in an all-butter crust. With a side of mixed fruits."},
  {name: "Green beans", price: 8, img_url: "https://loremflickr.com/300/300", description: "Creamy mascarpone cheese and custard layered between espresso and rum soaked house-made ladyfingers, topped with Valrhona cocoa powder."},
  {name: "Chilli Pepper", price: 2, img_url: "https://loremflickr.com/300/300", description: "Creamy mascarpone cheese and custard layered between espresso and rum soaked house-made ladyfingers, topped with Valrhona cocoa powder."},
  {name: "Bean Sprouts", price: 2, img_url: "https://loremflickr.com/300/300", description: "Three egg whites with spinach, mushrooms, caramelized onions, tomatoes and low-fat feta cheese. With herbed quinoa, and your choice of rye or whole-grain toast."},
  {name: "Bean Sprouts", price: 7, img_url: "https://loremflickr.com/300/300", description: "Fresh parsley, Italian sausage, shallots, garlic, sun-dried tomatoes and mozzarella cheese in an all-butter crust. With a side of mixed fruits."},
  {name: "Carrot", price: 2, img_url: "https://loremflickr.com/300/300", description: "Smoked salmon, poached eggs, diced red onions and Hollandaise sauce on an English muffin. With a side of roasted potatoes."},
  {name: "Red cabbage", price: 9, img_url: "https://loremflickr.com/300/300", description: "Fresh parsley, Italian sausage, shallots, garlic, sun-dried tomatoes and mozzarella cheese in an all-butter crust. With a side of mixed fruits."},
  {name: "Fresh Chillies", price: 2, img_url: "https://loremflickr.com/300/300", description: "Three egg whites with spinach, mushrooms, caramelized onions, tomatoes and low-fat feta cheese. With herbed quinoa, and your choice of rye or whole-grain toast."},
  {name: "Bean Sprouts", price: 6, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles, and a side of maple syrup."},
  {name: "Beans", price: 9, img_url: "https://loremflickr.com/300/300", description: "Fresh Norwegian salmon, lightly brushed with our herbed Dijon mustard sauce, with choice of two sides."},
  {name: "Jerusalem Artichoke", price: 4, img_url: "https://loremflickr.com/300/300", description: "Fresh parsley, Italian sausage, shallots, garlic, sun-dried tomatoes and mozzarella cheese in an all-butter crust. With a side of mixed fruits."},
  {name: "Radicchio", price: 3, img_url: "https://loremflickr.com/300/300", description: "Creamy mascarpone cheese and custard layered between espresso and rum soaked house-made ladyfingers, topped with Valrhona cocoa powder."},
  {name: "Snowpea sprouts", price: 0, img_url: "https://loremflickr.com/300/300", description: "Three egg omelet with Roquefort cheese, chives, and ham. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Peppers", price: 7, img_url: "https://loremflickr.com/300/300", description: "Granny Smith apples mixed with brown sugar and butter filling, in a flaky all-butter crust, with ice cream."},
  {name: "Jerusalem Artichoke", price: 0, img_url: "https://loremflickr.com/300/300", description: "Three eggs with cilantro, tomatoes, onions, avocados and melted Emmental cheese. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Hijiki", price: 4, img_url: "https://loremflickr.com/300/300", description: "Fresh Norwegian salmon, lightly brushed with our herbed Dijon mustard sauce, with choice of two sides."},
  {name: "Parsnip", price: 7, img_url: "https://loremflickr.com/300/300", description: "Two butter croissants of your choice (plain, almond or cheese). With a side of herb butter or house-made hazelnut spread."},
  {name: "Swiss Chard", price: 3, img_url: "https://loremflickr.com/300/300", description: "28-day aged 300g USDA Certified Prime Ribeye, rosemary-thyme garlic butter, with choice of two sides."},
  {name: "Rhubarb", price: 6, img_url: "https://loremflickr.com/300/300", description: "Granny Smith apples mixed with brown sugar and butter filling, in a flaky all-butter crust, with ice cream."},
  {name: "Sun dried tomatoes", price: 6, img_url: "https://loremflickr.com/300/300", description: "Creamy mascarpone cheese and custard layered between espresso and rum soaked house-made ladyfingers, topped with Valrhona cocoa powder."},
  {name: "Chives", price: 4, img_url: "https://loremflickr.com/300/300", description: "Fresh Norwegian salmon, lightly brushed with our herbed Dijon mustard sauce, with choice of two sides."},
  {name: "Carob Carrot", price: 1, img_url: "https://loremflickr.com/300/300", description: "Granny Smith apples mixed with brown sugar and butter filling, in a flaky all-butter crust, with ice cream."},
  {name: "Brussels Sprouts", price: 2, img_url: "https://loremflickr.com/300/300", description: "Two buttermilk waffles, topped with whipped cream and maple syrup, a side of two eggs served any style, and your choice of smoked bacon or smoked ham."},
  {name: "Purple carrot", price: 2, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles. Served with maple syrup."},
  {name: "Swiss Chard", price: 4, img_url: "https://loremflickr.com/300/300", description: "Fresh parsley, Italian sausage, shallots, garlic, sun-dried tomatoes and mozzarella cheese in an all-butter crust. With a side of mixed fruits."},
  {name: "Squash", price: 2, img_url: "https://loremflickr.com/300/300", description: "Thick slices of French toast bread, brown sugar, half-and-half and vanilla, topped with powdered sugar. With two eggs served any style, and your choice of smoked bacon or smoked ham."},
  {name: "English Spinach", price: 5, img_url: "https://loremflickr.com/300/300", description: "Creamy mascarpone cheese and custard layered between espresso and rum soaked house-made ladyfingers, topped with Valrhona cocoa powder."},
  {name: "Red cabbage", price: 6, img_url: "https://loremflickr.com/300/300", description: "Fresh parsley, Italian sausage, shallots, garlic, sun-dried tomatoes and mozzarella cheese in an all-butter crust. With a side of mixed fruits."},
  {name: "Cauliflower", price: 3, img_url: "https://loremflickr.com/300/300", description: "Thick slices of French toast bread, brown sugar, half-and-half and vanilla, topped with powdered sugar. With two eggs served any style, and your choice of smoked bacon or smoked ham."},
  {name: "Rhubarb", price: 8, img_url: "https://loremflickr.com/300/300", description: "Fresh parsley, Italian sausage, shallots, garlic, sun-dried tomatoes and mozzarella cheese in an all-butter crust. With a side of mixed fruits."},
  {name: "Rhubarb", price: 9, img_url: "https://loremflickr.com/300/300", description: "Fresh Norwegian salmon, lightly brushed with our herbed Dijon mustard sauce, with choice of two sides."},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Kale", price: 4, img_url: "https://loremflickr.com/300/300", description: "Fresh parsley, Italian sausage, shallots, garlic, sun-dried tomatoes and mozzarella cheese in an all-butter crust. With a side of mixed fruits."},
  {name: "Pumpkin", price: 8, img_url: "https://loremflickr.com/300/300", description: "Thick slices of French toast bread, brown sugar, half-and-half and vanilla, topped with powdered sugar. With two eggs served any style, and your choice of smoked bacon or smoked ham."},
  {name: "Squash", price: 6, img_url: "https://loremflickr.com/300/300", description: "Granny Smith apples mixed with brown sugar and butter filling, in a flaky all-butter crust, with ice cream."},
  {name: "Beans", price: 8, img_url: "https://loremflickr.com/300/300", description: "Smoked salmon, poached eggs, diced red onions and Hollandaise sauce on an English muffin. With a side of roasted potatoes."},
  {name: "Garlic", price: 8, img_url: "https://loremflickr.com/300/300", description: "28-day aged 300g USDA Certified Prime Ribeye, rosemary-thyme garlic butter, with choice of two sides."},
  {name: "Jerusalem Artichoke", price: 6, img_url: "https://loremflickr.com/300/300", description: "Three egg omelet with Roquefort cheese, chives, and ham. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Dried Chinese Broccoli", price: 3, img_url: "https://loremflickr.com/300/300", description: "Smoked salmon, poached eggs, diced red onions and Hollandaise sauce on an English muffin. With a side of roasted potatoes."},
  {name: "Red cabbage", price: 5, img_url: "https://loremflickr.com/300/300", description: "Thick slices of French toast bread, brown sugar, half-and-half and vanilla, topped with powdered sugar. With two eggs served any style, and your choice of smoked bacon or smoked ham."},
  {name: "Radish", price: 3, img_url: "https://loremflickr.com/300/300", description: "Fresh parsley, Italian sausage, shallots, garlic, sun-dried tomatoes and mozzarella cheese in an all-butter crust. With a side of mixed fruits."},
  {name: "Fresh Chillies", price: 0, img_url: "https://loremflickr.com/300/300", description: "Three eggs with cilantro, tomatoes, onions, avocados and melted Emmental cheese. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Beetroot", price: 7, img_url: "https://loremflickr.com/300/300", description: "28-day aged 300g USDA Certified Prime Ribeye, rosemary-thyme garlic butter, with choice of two sides."},
  {name: "Jerusalem Artichoke", price: 6, img_url: "https://loremflickr.com/300/300", description: "28-day aged 300g USDA Certified Prime Ribeye, rosemary-thyme garlic butter, with choice of two sides."},
  {name: "Okra", price: 2, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles, and a side of maple syrup."},
  {name: "Dried Chinese Broccoli", price: 9, img_url: "https://loremflickr.com/300/300", description: "Three egg omelet with Roquefort cheese, chives, and ham. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Endive", price: 9, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles. Served with maple syrup."},
  {name: "Raspberry", price: 4, img_url: "https://loremflickr.com/300/300", description: "Three eggs with cilantro, tomatoes, onions, avocados and melted Emmental cheese. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Jicama", price: 4, img_url: "https://loremflickr.com/300/300", description: "Granny Smith apples mixed with brown sugar and butter filling, in a flaky all-butter crust, with ice cream."},
  {name: "Cos lettuce", price: 4, img_url: "https://loremflickr.com/300/300", description: "Granny Smith apples mixed with brown sugar and butter filling, in a flaky all-butter crust, with ice cream."},
  {name: "Rhubarb", price: 2, img_url: "https://loremflickr.com/300/300", description: "Creamy mascarpone cheese and custard layered between espresso and rum soaked house-made ladyfingers, topped with Valrhona cocoa powder."},
  {name: "Leeks", price: 3, img_url: "https://loremflickr.com/300/300", description: "28-day aged 300g USDA Certified Prime Ribeye, rosemary-thyme garlic butter, with choice of two sides."},
  {name: "Cauliflower", price: 0, img_url: "https://loremflickr.com/300/300", description: "Smoked salmon, poached eggs, diced red onions and Hollandaise sauce on an English muffin. With a side of roasted potatoes."},
  {name: "Onion", price: 8, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles. Served with maple syrup."},
  {name: "Hijiki", price: 9, img_url: "https://loremflickr.com/300/300", description: "Three egg omelet with Roquefort cheese, chives, and ham. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Carrot", price: 8, img_url: "https://loremflickr.com/300/300", description: "Three egg omelet with Roquefort cheese, chives, and ham. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Endive", price: 5, img_url: "https://loremflickr.com/300/300", description: "Smoked salmon, poached eggs, diced red onions and Hollandaise sauce on an English muffin. With a side of roasted potatoes."},
  {name: "Squash", price: 8, img_url: "https://loremflickr.com/300/300", description: "Thick slices of French toast bread, brown sugar, half-and-half and vanilla, topped with powdered sugar. With two eggs served any style, and your choice of smoked bacon or smoked ham."},
  {name: "Fresh Chillies", price: 6, img_url: "https://loremflickr.com/300/300", description: "28-day aged 300g USDA Certified Prime Ribeye, rosemary-thyme garlic butter, with choice of two sides."},
  {name: "Parsnip", price: 4, img_url: "https://loremflickr.com/300/300", description: "Thick slices of French toast bread, brown sugar, half-and-half and vanilla, topped with powdered sugar. With two eggs served any style, and your choice of smoked bacon or smoked ham."},
  {name: "Purple carrot", price: 3, img_url: "https://loremflickr.com/300/300", description: "Fresh parsley, Italian sausage, shallots, garlic, sun-dried tomatoes and mozzarella cheese in an all-butter crust. With a side of mixed fruits."},
  {name: "Arugula", price: 8, img_url: "https://loremflickr.com/300/300", description: "Granny Smith apples mixed with brown sugar and butter filling, in a flaky all-butter crust, with ice cream."},
  {name: "Peas", price: 5, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles. Served with maple syrup."},
  {name: "French eschallots", price: 1, img_url: "https://loremflickr.com/300/300", description: "Three eggs with cilantro, tomatoes, onions, avocados and melted Emmental cheese. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Chilli Pepper", price: 3, img_url: "https://loremflickr.com/300/300", description: "Three eggs with cilantro, tomatoes, onions, avocados and melted Emmental cheese. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Cauliflower", price: 1, img_url: "https://loremflickr.com/300/300", description: "Fresh Norwegian salmon, lightly brushed with our herbed Dijon mustard sauce, with choice of two sides."},
  {name: "Turnips", price: 0, img_url: "https://loremflickr.com/300/300", description: "Smoked salmon, poached eggs, diced red onions and Hollandaise sauce on an English muffin. With a side of roasted potatoes."},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Asian Greens", price: 3, img_url: "https://loremflickr.com/300/300", description: "Three egg omelet with Roquefort cheese, chives, and ham. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Zucchini", price: 2, img_url: "https://loremflickr.com/300/300", description: "Two buttermilk waffles, topped with whipped cream and maple syrup, a side of two eggs served any style, and your choice of smoked bacon or smoked ham."},
  {name: "Rhubarb", price: 0, img_url: "https://loremflickr.com/300/300", description: "Two buttermilk waffles, topped with whipped cream and maple syrup, a side of two eggs served any style, and your choice of smoked bacon or smoked ham."},
  {name: "Bok Choy", price: 9, img_url: "https://loremflickr.com/300/300", description: "Fresh parsley, Italian sausage, shallots, garlic, sun-dried tomatoes and mozzarella cheese in an all-butter crust. With a side of mixed fruits."},
  {name: "Purple carrot", price: 2, img_url: "https://loremflickr.com/300/300", description: "Thick slices of French toast bread, brown sugar, half-and-half and vanilla, topped with powdered sugar. With two eggs served any style, and your choice of smoked bacon or smoked ham."},
  {name: "Beetroot", price: 1, img_url: "https://loremflickr.com/300/300", description: "28-day aged 300g USDA Certified Prime Ribeye, rosemary-thyme garlic butter, with choice of two sides."},
  {name: "Celery", price: 8, img_url: "https://loremflickr.com/300/300", description: "Fresh parsley, Italian sausage, shallots, garlic, sun-dried tomatoes and mozzarella cheese in an all-butter crust. With a side of mixed fruits."},
  {name: "Radish", price: 7, img_url: "https://loremflickr.com/300/300", description: "Smoked salmon, poached eggs, diced red onions and Hollandaise sauce on an English muffin. With a side of roasted potatoes."},
  {name: "Eggplant", price: 8, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles, and a side of maple syrup."},
  {name: "English Spinach", price: 2, img_url: "https://loremflickr.com/300/300", description: "Three egg whites with spinach, mushrooms, caramelized onions, tomatoes and low-fat feta cheese. With herbed quinoa, and your choice of rye or whole-grain toast."},
  {name: "Broccolini", price: 5, img_url: "https://loremflickr.com/300/300", description: "28-day aged 300g USDA Certified Prime Ribeye, rosemary-thyme garlic butter, with choice of two sides."},
  {name: "Radish", price: 5, img_url: "https://loremflickr.com/300/300", description: "28-day aged 300g USDA Certified Prime Ribeye, rosemary-thyme garlic butter, with choice of two sides."},
  {name: "Brussels Sprouts", price: 9, img_url: "https://loremflickr.com/300/300", description: "Three egg whites with spinach, mushrooms, caramelized onions, tomatoes and low-fat feta cheese. With herbed quinoa, and your choice of rye or whole-grain toast."},
  {name: "Hijiki", price: 7, img_url: "https://loremflickr.com/300/300", description: "Granny Smith apples mixed with brown sugar and butter filling, in a flaky all-butter crust, with ice cream."},
  {name: "Brussels Sprouts", price: 3, img_url: "https://loremflickr.com/300/300", description: "Smoked salmon, poached eggs, diced red onions and Hollandaise sauce on an English muffin. With a side of roasted potatoes."},
  {name: "Bean Shoots", price: 9, img_url: "https://loremflickr.com/300/300", description: "Fresh Norwegian salmon, lightly brushed with our herbed Dijon mustard sauce, with choice of two sides."},
  {name: "Iceberg lettuce", price: 7, img_url: "https://loremflickr.com/300/300", description: "Fresh parsley, Italian sausage, shallots, garlic, sun-dried tomatoes and mozzarella cheese in an all-butter crust. With a side of mixed fruits."},
  {name: "Turnips", price: 7, img_url: "https://loremflickr.com/300/300", description: "Three egg whites with spinach, mushrooms, caramelized onions, tomatoes and low-fat feta cheese. With herbed quinoa, and your choice of rye or whole-grain toast."},
  {name: "Sweet Potato", price: 5, img_url: "https://loremflickr.com/300/300", description: "Three eggs with cilantro, tomatoes, onions, avocados and melted Emmental cheese. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Bean Shoots", price: 5, img_url: "https://loremflickr.com/300/300", description: "Fresh parsley, Italian sausage, shallots, garlic, sun-dried tomatoes and mozzarella cheese in an all-butter crust. With a side of mixed fruits."},
  {name: "Radicchio", price: 7, img_url: "https://loremflickr.com/300/300", description: "Three egg whites with spinach, mushrooms, caramelized onions, tomatoes and low-fat feta cheese. With herbed quinoa, and your choice of rye or whole-grain toast."},
  {name: "Brussels Sprouts", price: 5, img_url: "https://loremflickr.com/300/300", description: "Two buttermilk waffles, topped with whipped cream and maple syrup, a side of two eggs served any style, and your choice of smoked bacon or smoked ham."},
  {name: "Jicama", price: 6, img_url: "https://loremflickr.com/300/300", description: "Three egg whites with spinach, mushrooms, caramelized onions, tomatoes and low-fat feta cheese. With herbed quinoa, and your choice of rye or whole-grain toast."},
  {name: "Bean Shoots", price: 3, img_url: "https://loremflickr.com/300/300", description: "Smoked salmon, poached eggs, diced red onions and Hollandaise sauce on an English muffin. With a side of roasted potatoes."},
  {name: "French eschallots", price: 1, img_url: "https://loremflickr.com/300/300", description: "Three egg omelet with Roquefort cheese, chives, and ham. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Celery", price: 6, img_url: "https://loremflickr.com/300/300", description: "Three eggs with cilantro, tomatoes, onions, avocados and melted Emmental cheese. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Spinach", price: 7, img_url: "https://loremflickr.com/300/300", description: "Three egg omelet with Roquefort cheese, chives, and ham. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Broccolini", price: 1, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles, and a side of maple syrup."},
  {name: "Beans", price: 6, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles. Served with maple syrup."},
  {name: "Cucumber", price: 6, img_url: "https://loremflickr.com/300/300", description: "28-day aged 300g USDA Certified Prime Ribeye, rosemary-thyme garlic butter, with choice of two sides."},
  {name: "Arugula", price: 8, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles, and a side of maple syrup."},
  {name: "Dried Chinese Broccoli", price: 6, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles. Served with maple syrup."},
  {name: "Cabbage", price: 8, img_url: "https://loremflickr.com/300/300", description: "Three egg whites with spinach, mushrooms, caramelized onions, tomatoes and low-fat feta cheese. With herbed quinoa, and your choice of rye or whole-grain toast."},
  {name: "Red cabbage", price: 3, img_url: "https://loremflickr.com/300/300", description: "Fresh parsley, Italian sausage, shallots, garlic, sun-dried tomatoes and mozzarella cheese in an all-butter crust. With a side of mixed fruits."},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Raspberry", price: 6, img_url: "https://loremflickr.com/300/300", description: "Thick slices of French toast bread, brown sugar, half-and-half and vanilla, topped with powdered sugar. With two eggs served any style, and your choice of smoked bacon or smoked ham."},
  {name: "Asian Greens", price: 1, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles. Served with maple syrup."},
  {name: "Cornichons", price: 8, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles, and a side of maple syrup."},
  {name: "Parsnip", price: 5, img_url: "https://loremflickr.com/300/300", description: "Two buttermilk waffles, topped with whipped cream and maple syrup, a side of two eggs served any style, and your choice of smoked bacon or smoked ham."},
  {name: "Chives", price: 0, img_url: "https://loremflickr.com/300/300", description: "Granny Smith apples mixed with brown sugar and butter filling, in a flaky all-butter crust, with ice cream."},
  {name: "Jicama", price: 4, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles, and a side of maple syrup."},
  {name: "Beetroot", price: 9, img_url: "https://loremflickr.com/300/300", description: "Three egg whites with spinach, mushrooms, caramelized onions, tomatoes and low-fat feta cheese. With herbed quinoa, and your choice of rye or whole-grain toast."},
  {name: "Kohlrabi", price: 6, img_url: "https://loremflickr.com/300/300", description: "Three eggs with cilantro, tomatoes, onions, avocados and melted Emmental cheese. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Kohlrabi", price: 9, img_url: "https://loremflickr.com/300/300", description: "28-day aged 300g USDA Certified Prime Ribeye, rosemary-thyme garlic butter, with choice of two sides."},
  {name: "Radish", price: 6, img_url: "https://loremflickr.com/300/300", description: "Three eggs with cilantro, tomatoes, onions, avocados and melted Emmental cheese. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Bean Shoots", price: 9, img_url: "https://loremflickr.com/300/300", description: "Smoked salmon, poached eggs, diced red onions and Hollandaise sauce on an English muffin. With a side of roasted potatoes."},
  {name: "Cos lettuce", price: 9, img_url: "https://loremflickr.com/300/300", description: "28-day aged 300g USDA Certified Prime Ribeye, rosemary-thyme garlic butter, with choice of two sides."},
  {name: "Butternut lettuce", price: 8, img_url: "https://loremflickr.com/300/300", description: "Two butter croissants of your choice (plain, almond or cheese). With a side of herb butter or house-made hazelnut spread."},
  {name: "Red Pepper", price: 9, img_url: "https://loremflickr.com/300/300", description: "Three eggs with cilantro, tomatoes, onions, avocados and melted Emmental cheese. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Cauliflower", price: 1, img_url: "https://loremflickr.com/300/300", description: "Three eggs with cilantro, tomatoes, onions, avocados and melted Emmental cheese. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Chilli Pepper", price: 7, img_url: "https://loremflickr.com/300/300", description: "Fresh parsley, Italian sausage, shallots, garlic, sun-dried tomatoes and mozzarella cheese in an all-butter crust. With a side of mixed fruits."},
  {name: "Endive", price: 2, img_url: "https://loremflickr.com/300/300", description: "Thick slices of French toast bread, brown sugar, half-and-half and vanilla, topped with powdered sugar. With two eggs served any style, and your choice of smoked bacon or smoked ham."},
  {name: "Bean Sprouts", price: 1, img_url: "https://loremflickr.com/300/300", description: "Fresh Norwegian salmon, lightly brushed with our herbed Dijon mustard sauce, with choice of two sides."},
  {name: "Bean Shoots", price: 4, img_url: "https://loremflickr.com/300/300", description: "Two buttermilk waffles, topped with whipped cream and maple syrup, a side of two eggs served any style, and your choice of smoked bacon or smoked ham."},
  {name: "Capers", price: 0, img_url: "https://loremflickr.com/300/300", description: "Two butter croissants of your choice (plain, almond or cheese). With a side of herb butter or house-made hazelnut spread."},
  {name: "Cos lettuce", price: 7, img_url: "https://loremflickr.com/300/300", description: "Three egg omelet with Roquefort cheese, chives, and ham. With a side of roasted potatoes, and your choice of toast or croissant."},
  {name: "Asparagus", price: 2, img_url: "https://loremflickr.com/300/300", description: "Thick slices of French toast bread, brown sugar, half-and-half and vanilla, topped with powdered sugar. With two eggs served any style, and your choice of smoked bacon or smoked ham."},
  {name: "Cabbage", price: 1, img_url: "https://loremflickr.com/300/300", description: "Granny Smith apples mixed with brown sugar and butter filling, in a flaky all-butter crust, with ice cream."},
  {name: "Jerusalem Artichoke", price: 5, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles. Served with maple syrup."},
  {name: "Endive", price: 9, img_url: "https://loremflickr.com/300/300", description: "Breaded fried chicken with waffles, and a side of maple syrup."},
  {name: "Green Pepper", price: 7, img_url: "https://loremflickr.com/300/300", description: "Fresh Norwegian salmon, lightly brushed with our herbed Dijon mustard sauce, with choice of two sides."},
  {name: nil, price: 2, img_url: "https://loremflickr.com/300/300", description: "Fresh Norwegian salmon, lightly brushed with our herbed Dijon mustard sauce, with choice of two sides."},
  {name: "laptop", price: 800, img_url: "", description: "conects to internet"},
  {name: "Mike", price: 1000000, img_url: "   ", description: "here is the sescription"},
  {name: "Mike", price: 1000000, img_url: "   ", description: "here is the sescription"},
  {name: "Mike", price: 1000000, img_url: "   ", description: "here is the sescription"},
  {name: "Mike", price: 1000000, img_url: "   ", description: "here is the sescription"},
  {name: "Mike", price: 1000000, img_url: "   ", description: "here is the sescription"},
  {name: "Mike", price: 1000000, img_url: "   ", description: "here is the sescription"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"},
  {name: "Cars", price: 1000, img_url: " ", description: "take you places"}
])
